language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
env:
  - CI=false REACT_APP_DEPLOY_ENV=travis
script:
  - yarn lint
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
